name: Deploy My Blog to Tencent Cloud Lighthouse

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: true # 使 Git Submodules 可用

      - name: 更新 Git Submodules 并切换到指定 Tag
        run: |
          git submodule update --init --recursive --remote
          cd themes/hugo-PaperMod
          git fetch --tags
          git checkout tags/v7.0
          cd ../..

      - name: 拉取文章内容
        run: |
          git clone https://github.com/xxrBear/blog-posts.git content/posts

      - name: 安装 Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.119.0" # 指定 Hugo 版本
          extended: true # 如果需要 SCSS/SASS 支持

      - name: 生成静态文件
        run: hugo -F --cleanDestinationDir

      - name: 通过 SSH 发送文件
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "public/*"
          target: "/home/ubuntu/myblog/flow/"
